# Generated by Django 4.2.3 on 2023-07-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=30)),
                ('taskDescription', models.CharField(max_length=500)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isCompleted', models.BooleanField()),
            ],
        ),
    ]
